version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: "${{DOCKER_USERNAME}}/frontend-image:latest"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    image: "${{DOCKER_USERNAME}}/backend-image:latest"
    ports:
      - "5000:5000"
